// <auto-generated/>
namespace SteganographyApp
{
    using System.Collections.Immutable;

    using SteganographyApp.Common;
    using SteganographyApp.Common.Arguments;
    using SteganographyApp.Common.Arguments.Commands;
    using SteganographyApp.Common.Injection;
    using SteganographyApp.Common.IO;

    [ProgramDescriptor("Cleans the LSBs of each pixel colour of the specified cover images.")]
    internal sealed class CleanArguments : IArgumentConverter
    {
        [Argument("--coverImages", "-c", true, helpText: "The list of images whose pixel colour LSBs need to be cleaned")]
        public ImmutableArray<string> CoverImages;

        public IInputArguments ToCommonArguments()
        {
            return new CommonArguments
            {
                CoverImages = this.CoverImages
            };
        }
    }

    internal sealed class CleanCoverImagesCommand : BaseCommand<CleanArguments>
    {
        public override void Execute(CleanArguments args)
        {
            Injector.LoggerFor<CleanCoverImagesCommand>().Trace("Cleaning image LSBs");
            var tracker = ProgressTracker.CreateAndDisplay(args.CoverImages.Length, "Cleaning image LSB data", "Finished cleaning all images.");
            var store = new ImageStore(args.ToCommonArguments());
            store.OnNextImageLoaded += (object? sender, NextImageLoadedEventArgs eventArg) =>
            {
                tracker.UpdateAndDisplayProgress();
            };
            store.CleanImageLSBs();
        }

        public override string GetName() => "clean";
    }

}