// <auto-generated/>
namespace SteganographyApp
{
    using System.Collections.Immutable;

    using SteganographyApp.Common;
    using SteganographyApp.Common.Arguments;
    using SteganographyApp.Common.Arguments.Commands;
    using SteganographyApp.Common.Injection;
    using SteganographyApp.Common.IO;

    [ProgramDescriptor("Cleans the LSBs of each pixel colour of the specified cover images.")]
    internal sealed class CleanArguments : IArgumentConverter
    {
        [Argument("CoverImages", position: 1, helpText: "The list of images whose pixel colour LSBs need to be cleaned.\n"
            + " This parameter can be a comma delimited list of globs with the current directory as the root directory from which files will be matched.")]
        public ImmutableArray<string> CoverImages = new ImmutableArray<string>();

        [Argument("--twoBits", "-tb", helpText: "If true will store data in the least and second-least significant bit rather than just the least significant.")]
        public bool TwoBits = false;

        public IInputArguments ToCommonArguments()
        {
            return new CommonArguments
            {
                CoverImages = this.CoverImages,
                BitsToUse = TwoBits ? 2 : 1,
            };
        }
    }

    internal sealed class CleanCoverImagesCommand : BaseCommand<CleanArguments>
    {
        public override void Execute(CleanArguments args)
        {
            Injector.LoggerFor<CleanCoverImagesCommand>().Trace("Cleaning image LSBs");
            var tracker = ProgressTracker.CreateAndDisplay(args.CoverImages.Length, "Cleaning image LSB data", "Finished cleaning all images.");
            var store = new ImageStore(args.ToCommonArguments());
            store.OnNextImageLoaded += (object? sender, NextImageLoadedEventArgs eventArg) =>
            {
                tracker.UpdateAndDisplayProgress();
            };
            store.CleanImages();
        }

        public override string GetName() => "clean";
    }

}