// <auto-generated/>
namespace SteganographyApp
{
    using System.Collections.Immutable;
    using System.Text.Json;

    using SteganographyApp.Common.Arguments;
    using SteganographyApp.Common.Injection;
    using SteganographyApp.Common.Logging;

    [ProgramDescriptor("Decode data from the specified cover images to the output file.")]
    public sealed class DecodeArguments : IArgumentConverter
    {
        [Argument("--coverImages", "-c", true, helpText: "The images where the input file will be decoded from.")]
        public ImmutableArray<string> CoverImages = new ImmutableArray<string>();

        [Argument("--password", "-p", helpText: "The optional password used to decrypt the input file contents.")]
        public string Password = string.Empty;

        [Argument("--out", "-o", true, helpText: "The path to the file where the decoded contents will be written to.")]
        public string OutputFile = string.Empty;

        [Argument("--randomSeed", "-r", helpText: "The optional value to determine how the contents cover image contents will be decoded while before writing them to the output file.")]
        public string RandomSeed = string.Empty;

        [Argument("--dummyCount", "-d", helpText: "The number of dummy entries to be removed after randomization and before decryption. Recommended value between 100 and 1,000.")]
        public int DummyCount = 0;

        [Argument("--logLevel", "-l", helpText: "The log level to determine which logs will feed into the log file.")]
        public LogLevel LogLevel = LogLevel.None;

        [Argument("--additionalHashes", "-a", helpText: "The number of additional times to has the password. Has no effect if no password is provided.")]
        public int AdditionalPasswordHashIterations = 0;

        public IInputArguments ToCommonArguments()
        {
            RootLogger.Instance.EnableLoggingAtLevel(LogLevel);
            var arguments = new CommonArguments
            {
                CoverImages = CoverImages,
                Password = Password,
                DecodedOutputFile = OutputFile,
                RandomSeed = RandomSeed,
                DummyCount = DummyCount,
                AdditionalPasswordHashIterations = AdditionalPasswordHashIterations,
            };
            Injector.LoggerFor<DecodeArguments>().Debug("Using input arguments: [{0}]", () => new[] { JsonSerializer.Serialize(arguments) });
            return arguments;
        }
    }
}