// <auto-generated/>
namespace SteganographyApp
{
    using System.Collections.Immutable;
    using System.Text.Json;

    using SteganographyApp.Common.Arguments;
    using SteganographyApp.Common.Injection;
    using SteganographyApp.Common.Logging;

    [ProgramDescriptor("Decode data from the specified cover images to the output file.")]
    public sealed class DecodeArguments : IArgumentConverter
    {
        [Argument("--coverImages", "-c", true, helpText: "The images where the input file will be decoded from.")]
        public ImmutableArray<string> CoverImages;

        [Argument("--password", "-p", helpText: "The optional password used to decrypt the input file contents.")]
        public string Password = string.Empty;

        [Argument("--out", "-o", true, helpText: "The path to the file where the decoded contents will be written to.")]
        public string OutputFile = string.Empty;

        [Argument("--randomSeed", "-r", helpText: "The optional value to determine how the contents cover image contents will be decoded while before writing them to the output file.")]
        public string RandomSeed = string.Empty;

        [Argument("--insertDummies", "-i", helpText: "Choose whether dummy values need to be removed from the encoded cover image contents.")]
        public bool InsertDummies = false;

        [Argument("--logLevel", "-l", helpText: "The log level to determine which logs will feed into the log file.")]
        public LogLevel LogLevel = LogLevel.None;

        public IInputArguments ToCommonArguments()
        {
            RootLogger.Instance.EnableLoggingAtLevel(LogLevel);
            var arguments = new CommonArguments
            {
                CoverImages = CoverImages,
                Password = Password,
                DecodedOutputFile = OutputFile,
                RandomSeed = RandomSeed,
                InsertDummies = InsertDummies,
                DummyCount = ParserFunctions.ParseDummyCount(InsertDummies, CoverImages, RandomSeed)
            };
            Injector.LoggerFor<EncodeArguments>().Debug("Using input arguments: [{0}]", () => new[] { JsonSerializer.Serialize(arguments) });
            return arguments;
        }
    }
}